### PR TITLE
Tensorboard added for loss function graph and steering wheel background changed

### PR DESCRIPTION
**Pull request by gautamsharma7234**
Tensorboard added to train.py for visualizing loss function. To visualize loss function, open a new terminal and use command "tensorboard --logdir=./logs". Now, open http://0.0.0.0:6006/ in your browser.

Steering wheel background changed to black since white background causes the image to rotate entirely which doesn't looks good for visualizing turning motion of the steering wheel.

### CODE REVIEW

**Comment by SullyChen** [comment]
Wow this is awesome, excellent job on this.

**Comment by gautamsharma7234** [comment]
Thanks Sully. Btw, your work is really awesome on this too. It helped me a lot. so thanks a lot for it :)

**Comment by SullyChen** [comment]
No problem! Glad I could help.

**Comment by gautamsharma7234** [comment]
Hey Sully, I checked the list of contributors of this repo but my name isn't showing up. Sorry for such a naive question. I'm new to github.

**Comment by SullyChen** [comment]
I'm not sure either. I don't use GitHub often. Maybe it takes time to process? I'll try to look for a way to add you manually right now.

**Comment by gautamsharma7234** [comment]
Thanks! I really appreciate your help.

**Pull request merged**
